### ISSUE TITLE
In wired-input text overflows from border

### ISSUE THREAD

**Issue by Sasha2018RL** [rough-stuff/wired-elements#138] opened 2020-04-16 16:31 UTC
I tried to resize `wired-input` element using standard CSS `width `property. Border of input element has  same width as before, but if I type text, longer than width of border it overflows.
![image](https://user-images.githubusercontent.com/43745163/79482027-ea7f4080-8018-11ea-94ac-8dadad43a2a0.png)

**Comment by apennamen** [comment] 2020-04-19 12:01
Hello,
I'm not reproducing this issue, neither on the showcase nor with the source code of wired-input.

How did you apply the width ? 
If you apply a different width to the input inside the wired-input (in the shadow dom), you will indeed have this result.
Normally when applying width directly to the wired-input element (either via style attribute or with css), you won't have this behaviour

**Comment by pshihn** [comment] 2020-06-20 06:57
This can happen if the CSS style is applied after the element is rendered. 
I have since updated the input to listen to resize observer. Should be fixed in v2.1.1

**Closed by pshihn** 2020-06-20 06:57 UTC
